apiVersion: v1
kind: Service
metadata:
  name: svc-calc
spec:
  type: LoadBalancer
  selector:
    laravel: calc
  ports:
    - protocol: TCP
      nodePort: 30008
      port: 8000
      targetPort: 8000    
